// Styles for AgriGuard AI - Farmer-Friendly Version

export const styles = {
  app: {
    fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
    background: "#f7f3ed",
    minHeight: "100vh",
    maxWidth: 480,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    background: "linear-gradient(135deg, #2d6a4f, #52b788)",
    padding: "16px",
    color: "white",
  },
  headerTitle: {
    fontWeight: 900,
    fontSize: 22,
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  headerActions: {
    display: "flex",
    gap: 8,
    marginTop: 10,
  },
  langBtn: {
    background: "rgba(255,255,255,0.2)",
    color: "white",
    border: "none",
    borderRadius: 12,
    padding: "8px 14px",
    fontSize: 14,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  content: {
    flex: 1,
    padding: "16px",
    paddingBottom: 120,
    overflowY: "auto",
  },
  card: {
    background: "white",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
  },
  // Quick Action Buttons on Home
  quickActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    marginBottom: 16,
  },
  quickActionBtn: {
    background: "white",
    border: "none",
    borderRadius: 16,
    padding: 20,
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    transition: "transform 0.2s",
  },
  quickActionIcon: {
    fontSize: 36,
  },
  quickActionText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#2d6a4f",
  },
  // Large prominent scan button
  scanBtn: {
    background: "linear-gradient(135deg, #16a34a, #22c55e)",
    color: "white",
    border: "none",
    borderRadius: 16,
    padding: "20px 24px",
    fontSize: 18,
    fontWeight: "bold",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    boxShadow: "0 4px 12px rgba(22, 163, 74, 0.4)",
    marginBottom: 16,
  },
  tabBar: {
    position: "fixed",
    bottom: 0,
    width: "100%",
    maxWidth: 480,
    background: "white",
    display: "flex",
    borderTop: "1px solid #ddd",
    paddingBottom: "env(safe-area-inset-bottom)",
    boxShadow: "0 -2px 10px rgba(0,0,0,0.1)",
  },
  tabBtn: (active) => ({
    flex: 1,
    padding: "12px 4px",
    border: "none",
    background: active ? "#f0fdf4" : "white",
    color: active ? "#2d6a4f" : "#666",
    fontSize: "12px",
    fontWeight: "bold",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
  }),
  tabIcon: {
    fontSize: 22,
  },
  bigBtn: {
    width: "100%",
    padding: "16px",
    borderRadius: 14,
    border: "none",
    fontSize: 16,
    fontWeight: "bold",
    cursor: "pointer",
    marginTop: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  pill: (c, bg) => ({
    background: bg,
    color: c,
    padding: "6px 12px",
    borderRadius: 14,
    fontSize: 13,
    fontWeight: "bold",
  }),
  input: {
    width: "100%",
    padding: "14px",
    borderRadius: 12,
    border: "1px solid #ddd",
    fontSize: 16,
    marginBottom: 10,
  },
  // Voice input button
  voiceBtn: {
    width: 48,
    height: 48,
    borderRadius: "50%",
    border: "none",
    background: "#16a34a",
    color: "white",
    fontSize: 20,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  voiceBtnActive: {
    background: "#dc2626",
    animation: "pulse 1s infinite",
  },
  // Status indicators
  statusBadge: (status) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: "500",
    background: status === "success" ? "#dcfce7" : status === "warning" ? "#fef3c7" : status === "error" ? "#fee2e2" : "#e0f2fe",
    color: status === "success" ? "#166534" : status === "warning" ? "#92400e" : status === "error" ? "#991b1b" : "#075985",
  }),
  // Onboarding
  onboardingCard: {
    background: "white",
    borderRadius: 20,
    padding: 24,
    marginBottom: 16,
    textAlign: "center",
    boxShadow: "0 4px 20px rgba(0,0,0,0.1)",
  },
  onboardingTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#2d6a4f",
    marginBottom: 12,
  },
  onboardingDesc: {
    fontSize: 15,
    color: "#4b5563",
    lineHeight: 1.5,
    marginBottom: 20,
  },
  stepIndicator: {
    display: "flex",
    justifyContent: "center",
    gap: 8,
    marginBottom: 20,
  },
  stepDot: (active, completed) => ({
    width: active ? 24 : 10,
    height: 10,
    borderRadius: 5,
    background: completed ? "#16a34a" : active ? "#22c55e" : "#d1d5db",
    transition: "all 0.3s",
  }),
  // Weather card
  weatherCard: {
    background: "linear-gradient(135deg, #3b82f6, #60a5fa)",
    color: "white",
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  weatherTemp: {
    fontSize: 42,
    fontWeight: "bold",
  },
  weatherInfo: {
    display: "flex",
    gap: 16,
    marginTop: 10,
    fontSize: 14,
  },
  // Alert banner
  alertBanner: {
    background: "#fef3c7",
    border: "1px solid #f59e0b",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    display: "flex",
    alignItems: "center",
    gap: 10,
    cursor: "pointer",
  },
  // Loading states
  loading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    gap: 10,
    color: "#6b7280",
  },

  // Login Screen
  loginOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "linear-gradient(135deg, #2d6a4f, #52b788)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 20,
  },
  loginCard: {
    background: "white",
    borderRadius: 24,
    padding: 32,
    width: "100%",
    maxWidth: 360,
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
  },
  loginHeader: {
    textAlign: "center",
    marginBottom: 24,
  },
  loginLogo: {
    fontSize: 48,
    display: "block",
    marginBottom: 12,
  },
  loginTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#2d6a4f",
    margin: "0 0 8px",
  },
  loginSubtitle: {
    color: "#6b7280",
    margin: 0,
    fontSize: 14,
  },
  loginError: {
    background: "#fee2e2",
    color: "#dc2626",
    padding: "12px 16px",
    borderRadius: 12,
    marginBottom: 16,
    fontSize: 14,
    textAlign: "center",
  },
  formGroup: {
    marginBottom: 16,
  },
  formLabel: {
    display: "block",
    fontWeight: "600",
    marginBottom: 8,
    color: "#374151",
    fontSize: 14,
  },
  formInput: {
    width: "100%",
    padding: "14px 16px",
    borderRadius: 12,
    border: "2px solid #e5e7eb",
    fontSize: 16,
    outline: "none",
    transition: "border-color 0.2s",
    boxSizing: "border-box",
  },
  formHint: {
    display: "block",
    marginTop: 6,
    color: "#9ca3af",
    fontSize: 12,
  },
  loginButton: {
    width: "100%",
    padding: "16px",
    borderRadius: 14,
    border: "none",
    fontSize: 16,
    fontWeight: "bold",
    cursor: "pointer",
    background: "linear-gradient(135deg, #16a34a, #22c55e)",
    color: "white",
    boxShadow: "0 4px 12px rgba(22, 163, 74, 0.4)",
    transition: "transform 0.2s",
  },
  loginButtonDisabled: {
    width: "100%",
    padding: "16px",
    borderRadius: 14,
    border: "none",
    fontSize: 16,
    fontWeight: "bold",
    cursor: "not-allowed",
    background: "#9ca3af",
    color: "white",
  },
  loginToggle: {
    textAlign: "center",
    marginTop: 16,
    color: "#6b7280",
    fontSize: 14,
  },
  linkButton: {
    background: "none",
    border: "none",
    color: "#16a34a",
    fontWeight: "600",
    cursor: "pointer",
    textDecoration: "underline",
    fontSize: 14,
  },
  skipButton: {
    width: "100%",
    padding: "12px",
    marginTop: 16,
    border: "none",
    background: "transparent",
    color: "#9ca3af",
    fontSize: 14,
    cursor: "pointer",
  },
  // User logged in indicator
  userBadge: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "rgba(255,255,255,0.2)",
    padding: "6px 12px",
    borderRadius: 20,
    fontSize: 13,
    cursor: "pointer",
  },
};

export default styles;

